#!/usr/bin/env bash
DOCKER_BUILDKIT=1

docker build --pull -t php-base:7.1 -f dockerfile71 .

docker build --pull -t php-base:7.3 -f dockerfile73 .

docker build --pull -t php-base:8.1 -f dockerfile81 .

docker build --pull -t php-base:8.2 -t php-base:latest -f dockerfile82 .
docker build --pull -t php-base:8.2-mongodb -f dockerfile82 --target mongodb .

docker build --pull -t php-base:8.3 -t php-base:latest -f dockerfile83 --target base .
docker build --pull -t php-base:8.3-mongodb -t php-base:latest-mongodb -f dockerfile83 --target mongodb .
