#!/usr/bin/env bash
docker pull php:8.1-apache
docker build -t php-base:8.1 -f dockerfile81 .

docker pull php:8.2-apache
docker build -t php-base:8.2 -t php-base:latest -f dockerfile82 .

docker build -t php-base:8.1-mongodb -f dockerfile81-mongodb .
docker build -t php-base:8.2-mongodb -t php-base:latest-mongodb -f dockerfile82-mongodb .
